<a href="https://colab.research.google.com/github/ac477405-wq/abhishek/blob/main/DHPproject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
data=pd.read_csv("healthcare_dataset.csv")

In [14]:
#1.Find the most common disease.
data.value_counts("Medical Condition").idxmax()

'Arthritis'

In [16]:
#2. Calculate average treatment cost per disease.
data.groupby("Medical Condition")["Billing Amount"].mean()

Medical Condition
Arthritis       25497.327056
Asthma          25635.249359
Cancer          25161.792707
Diabetes        25638.405577
Hypertension    25497.095761
Obesity         25805.971259
Name: Billing Amount, dtype: float64

In [18]:
#3.Find total patients per hospital branch.
data.value_counts("Hospital")

Hospital
LLC Smith                        44
Ltd Smith                        39
Johnson PLC                      38
Smith Ltd                        37
Smith Group                      36
                                 ..
Jimenez, Bailey and Frederick     1
Jimenez, Bradley and Jacobs       1
Jimenez, Brennan Craig and        1
Jimenez, Green and Wright         1
Jimenez and Gross, Hogan          1
Name: count, Length: 39876, dtype: int64

In [23]:
#4.Identify patients older than 60.
data.loc[data["Age"]>60]["Name"]

1            LesLie TErRy
2             DaNnY sMitH
8         JASmINe aGuIlaR
10       mIchElLe daniELs
12          connOR HANsEn
               ...
55487      mIsTy RICharDs
55489      ANdrEw AGUIlaR
55490    STepHAniE oliVer
55494       JEssIcA WHiTe
55496          KYle pEREz
Name: Name, Length: 20370, dtype: object

In [28]:
#5. Find the branch with highest treatment cost.
a=data["Billing Amount"].max()
d=data.loc[data["Billing Amount"]==a]
d["Hospital"]

36349    Griffin Group
Name: Hospital, dtype: object

In [29]:
#6. Calculate average age of patients per disease.
data.groupby("Medical Condition")["Age"].mean()

Medical Condition
Arthritis       51.565320
Asthma          51.575830
Cancer          51.558795
Diabetes        51.554170
Hypertension    51.741915
Obesity         51.240277
Name: Age, dtype: float64

In [30]:
#7. Find top 5 highest treatment cost patients.
data.sort_values("Billing Amount",ascending=False).head(5)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
36349,tOdd CARrILlO,51,Female,A+,Hypertension,2023-09-08,Kathleen Griffin,Griffin Group,Blue Cross,52764.276736,209,Elective,2023-10-04,Ibuprofen,Normal
34613,kARen klInE,79,Female,AB+,Cancer,2021-06-19,Dr. Joseph Gordon,Hernandez-Morton,UnitedHealthcare,52373.032374,181,Urgent,2021-07-03,Penicillin,Inconclusive
51313,kARen klInE,74,Female,AB+,Cancer,2021-06-19,Dr. Joseph Gordon,Hernandez-Morton,UnitedHealthcare,52373.032374,181,Urgent,2021-07-03,Penicillin,Inconclusive
5735,DAVId SanDOvaL,22,Male,AB-,Hypertension,2019-11-02,Taylor Novak,Sons and Bailey,Blue Cross,52271.663747,228,Emergency,2019-11-11,Ibuprofen,Normal
7088,kathRYN GoNzales,18,Female,O+,Diabetes,2020-08-11,Kristin Clark,Miller Ltd,Aetna,52211.852966,383,Urgent,2020-08-12,Paracetamol,Inconclusive

In [31]:
#8. Count patients by gender.
data.groupby("Gender").size()

Gender
Female    27726
Male      27774
dtype: int64

In [32]:
#9.Identify disease with highest treatment cost.
a=data["Billing Amount"].max()
d=data.loc[data["Billing Amount"]==a]
d["Medical Condition"]

36349    Hypertension
Name: Medical Condition, dtype: object

In [33]:
#10. Calculate monthly patient admissions.
data["Date of Admission"]=pd.to_datetime(data["Date of Admission"])
data.groupby(data["Date of Admission"].dt.to_period("M")).size()

Date of Admission
2019-05     686
2019-06     907
2019-07     957
2019-08    1001
2019-09     936
           ...
2024-01     909
2024-02     880
2024-03     906
2024-04     946
2024-05     213
Freq: M, Length: 61, dtype: int64

In [34]:
data

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal